# Generated by Django 2.0.2 on 2019-09-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_goodsimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='轮播图片'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='封面图'),
        ),
        migrations.AddField(
            model_name='goodscategorybrand',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='brands/'),
        ),
    ]
